language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: nate@theoestudio.com
  api_key:
    secure: enter-key-here
  on:
    tags: true
    repo: NathanielInman/slush-jugs
    all_branches: true
